// Generated by gencpp from file acg_control_msg/FollowWorkspaceTrajectoryAction.msg
// DO NOT EDIT!


#ifndef ACG_CONTROL_MSG_MESSAGE_FOLLOWWORKSPACETRAJECTORYACTION_H
#define ACG_CONTROL_MSG_MESSAGE_FOLLOWWORKSPACETRAJECTORYACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <acg_control_msg/FollowWorkspaceTrajectoryActionGoal.h>
#include <acg_control_msg/FollowWorkspaceTrajectoryActionResult.h>
#include <acg_control_msg/FollowWorkspaceTrajectoryActionFeedback.h>

namespace acg_control_msg
{
template <class ContainerAllocator>
struct FollowWorkspaceTrajectoryAction_
{
  typedef FollowWorkspaceTrajectoryAction_<ContainerAllocator> Type;

  FollowWorkspaceTrajectoryAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  FollowWorkspaceTrajectoryAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::acg_control_msg::FollowWorkspaceTrajectoryActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::acg_control_msg::FollowWorkspaceTrajectoryActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWorkspaceTrajectoryAction_

typedef ::acg_control_msg::FollowWorkspaceTrajectoryAction_<std::allocator<void> > FollowWorkspaceTrajectoryAction;

typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryAction > FollowWorkspaceTrajectoryActionPtr;
typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryAction const> FollowWorkspaceTrajectoryActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator1> & lhs, const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator1> & lhs, const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acg_control_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28943193602e285b1572c5ce76aa6c00";
  }

  static const char* value(const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28943193602e285bULL;
  static const uint64_t static_value2 = 0x1572c5ce76aa6c00ULL;
};

template<class ContainerAllocator>
struct DataType< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acg_control_msg/FollowWorkspaceTrajectoryAction";
  }

  static const char* value(const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"FollowWorkspaceTrajectoryActionGoal action_goal\n"
"FollowWorkspaceTrajectoryActionResult action_result\n"
"FollowWorkspaceTrajectoryActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: acg_control_msg/FollowWorkspaceTrajectoryActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"FollowWorkspaceTrajectoryGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: acg_control_msg/FollowWorkspaceTrajectoryGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"workspace_trajectory_msgs/WorkspaceTrajectory workspace_trajectory\n"
"\n"
"================================================================================\n"
"MSG: workspace_trajectory_msgs/WorkspaceTrajectory\n"
"string name\n"
"geometry_msgs/Pose[] waypoints\n"
"geometry_msgs/Wrench[] wrenches\n"
"float64[] timestamps\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: acg_control_msg/FollowWorkspaceTrajectoryActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"FollowWorkspaceTrajectoryResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: acg_control_msg/FollowWorkspaceTrajectoryResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: acg_control_msg/FollowWorkspaceTrajectoryActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"FollowWorkspaceTrajectoryFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: acg_control_msg/FollowWorkspaceTrajectoryFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/Pose desired_pose\n"
"geometry_msgs/Wrench desired_wrench\n"
"geometry_msgs/Pose actual_pose\n"
"geometry_msgs/Wrench actual_wrench\n"
"geometry_msgs/Pose error_pose\n"
"geometry_msgs/Wrench error_wrench\n"
"std_msgs/Duration time_from_start\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Duration\n"
"duration data\n"
;
  }

  static const char* value(const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWorkspaceTrajectoryAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acg_control_msg::FollowWorkspaceTrajectoryAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::acg_control_msg::FollowWorkspaceTrajectoryActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::acg_control_msg::FollowWorkspaceTrajectoryActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACG_CONTROL_MSG_MESSAGE_FOLLOWWORKSPACETRAJECTORYACTION_H
