// Generated by gencpp from file acg_control_msg/FollowWorkspaceTrajectoryActionGoal.msg
// DO NOT EDIT!


#ifndef ACG_CONTROL_MSG_MESSAGE_FOLLOWWORKSPACETRAJECTORYACTIONGOAL_H
#define ACG_CONTROL_MSG_MESSAGE_FOLLOWWORKSPACETRAJECTORYACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <acg_control_msg/FollowWorkspaceTrajectoryGoal.h>

namespace acg_control_msg
{
template <class ContainerAllocator>
struct FollowWorkspaceTrajectoryActionGoal_
{
  typedef FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> Type;

  FollowWorkspaceTrajectoryActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FollowWorkspaceTrajectoryActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::acg_control_msg::FollowWorkspaceTrajectoryGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWorkspaceTrajectoryActionGoal_

typedef ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<std::allocator<void> > FollowWorkspaceTrajectoryActionGoal;

typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal > FollowWorkspaceTrajectoryActionGoalPtr;
typedef boost::shared_ptr< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal const> FollowWorkspaceTrajectoryActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator1> & lhs, const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator1> & lhs, const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acg_control_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c0ccf8ed1a83f14c9bbf6672531f0e1";
  }

  static const char* value(const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c0ccf8ed1a83f14ULL;
  static const uint64_t static_value2 = 0xc9bbf6672531f0e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acg_control_msg/FollowWorkspaceTrajectoryActionGoal";
  }

  static const char* value(const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"FollowWorkspaceTrajectoryGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: acg_control_msg/FollowWorkspaceTrajectoryGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"workspace_trajectory_msgs/WorkspaceTrajectory workspace_trajectory\n"
"\n"
"================================================================================\n"
"MSG: workspace_trajectory_msgs/WorkspaceTrajectory\n"
"string name\n"
"geometry_msgs/Pose[] waypoints\n"
"geometry_msgs/Wrench[] wrenches\n"
"float64[] timestamps\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWorkspaceTrajectoryActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acg_control_msg::FollowWorkspaceTrajectoryActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::acg_control_msg::FollowWorkspaceTrajectoryGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACG_CONTROL_MSG_MESSAGE_FOLLOWWORKSPACETRAJECTORYACTIONGOAL_H
