// Generated by gencpp from file ur10_python_interface/SolveIk.msg
// DO NOT EDIT!


#ifndef UR10_PYTHON_INTERFACE_MESSAGE_SOLVEIK_H
#define UR10_PYTHON_INTERFACE_MESSAGE_SOLVEIK_H

#include <ros/service_traits.h>


#include <ur10_python_interface/SolveIkRequest.h>
#include <ur10_python_interface/SolveIkResponse.h>


namespace ur10_python_interface
{

struct SolveIk
{

typedef SolveIkRequest Request;
typedef SolveIkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveIk
} // namespace ur10_python_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_python_interface::SolveIk > {
  static const char* value()
  {
    return "6580254afbe9e0087fa243dc6fb4dd77";
  }

  static const char* value(const ::ur10_python_interface::SolveIk&) { return value(); }
};

template<>
struct DataType< ::ur10_python_interface::SolveIk > {
  static const char* value()
  {
    return "ur10_python_interface/SolveIk";
  }

  static const char* value(const ::ur10_python_interface::SolveIk&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_python_interface::SolveIkRequest> should match
// service_traits::MD5Sum< ::ur10_python_interface::SolveIk >
template<>
struct MD5Sum< ::ur10_python_interface::SolveIkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_python_interface::SolveIk >::value();
  }
  static const char* value(const ::ur10_python_interface::SolveIkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_python_interface::SolveIkRequest> should match
// service_traits::DataType< ::ur10_python_interface::SolveIk >
template<>
struct DataType< ::ur10_python_interface::SolveIkRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_python_interface::SolveIk >::value();
  }
  static const char* value(const ::ur10_python_interface::SolveIkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_python_interface::SolveIkResponse> should match
// service_traits::MD5Sum< ::ur10_python_interface::SolveIk >
template<>
struct MD5Sum< ::ur10_python_interface::SolveIkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_python_interface::SolveIk >::value();
  }
  static const char* value(const ::ur10_python_interface::SolveIkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_python_interface::SolveIkResponse> should match
// service_traits::DataType< ::ur10_python_interface::SolveIk >
template<>
struct DataType< ::ur10_python_interface::SolveIkResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_python_interface::SolveIk >::value();
  }
  static const char* value(const ::ur10_python_interface::SolveIkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_PYTHON_INTERFACE_MESSAGE_SOLVEIK_H
