(cl:defpackage acg_control_msg-msg
  (:use )
  (:export
   "<FOLLOWWORKSPACETRAJECTORYACTION>"
   "FOLLOWWORKSPACETRAJECTORYACTION"
   "<FOLLOWWORKSPACETRAJECTORYACTIONFEEDBACK>"
   "FOLLOWWORKSPACETRAJECTORYACTIONFEEDBACK"
   "<FOLLOWWORKSPACETRAJECTORYACTIONGOAL>"
   "FOLLOWWORKSPACETRAJECTORYACTIONGOAL"
   "<FOLLOWWORKSPACETRAJECTORYACTIONRESULT>"
   "FOLLOWWORKSPACETRAJECTORYACTIONRESULT"
   "<FOLLOWWORKSPACETRAJECTORYFEEDBACK>"
   "FOLLOWWORKSPACETRAJECTORYFEEDBACK"
   "<FOLLOWWORKSPACETRAJECTORYGOAL>"
   "FOLLOWWORKSPACETRAJECTORYGOAL"
   "<FOLLOWWORKSPACETRAJECTORYRESULT>"
   "FOLLOWWORKSPACETRAJECTORYRESULT"
  ))

