; Auto-generated. Do not edit!


(cl:in-package acg_control_msg-msg)


;//! \htmlinclude FollowWorkspaceTrajectoryResult.msg.html

(cl:defclass <FollowWorkspaceTrajectoryResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass FollowWorkspaceTrajectoryResult (<FollowWorkspaceTrajectoryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowWorkspaceTrajectoryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowWorkspaceTrajectoryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acg_control_msg-msg:<FollowWorkspaceTrajectoryResult> is deprecated: use acg_control_msg-msg:FollowWorkspaceTrajectoryResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <FollowWorkspaceTrajectoryResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acg_control_msg-msg:success-val is deprecated.  Use acg_control_msg-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowWorkspaceTrajectoryResult>) ostream)
  "Serializes a message object of type '<FollowWorkspaceTrajectoryResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowWorkspaceTrajectoryResult>) istream)
  "Deserializes a message object of type '<FollowWorkspaceTrajectoryResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowWorkspaceTrajectoryResult>)))
  "Returns string type for a message object of type '<FollowWorkspaceTrajectoryResult>"
  "acg_control_msg/FollowWorkspaceTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowWorkspaceTrajectoryResult)))
  "Returns string type for a message object of type 'FollowWorkspaceTrajectoryResult"
  "acg_control_msg/FollowWorkspaceTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowWorkspaceTrajectoryResult>)))
  "Returns md5sum for a message object of type '<FollowWorkspaceTrajectoryResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowWorkspaceTrajectoryResult)))
  "Returns md5sum for a message object of type 'FollowWorkspaceTrajectoryResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowWorkspaceTrajectoryResult>)))
  "Returns full string definition for message of type '<FollowWorkspaceTrajectoryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowWorkspaceTrajectoryResult)))
  "Returns full string definition for message of type 'FollowWorkspaceTrajectoryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowWorkspaceTrajectoryResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowWorkspaceTrajectoryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowWorkspaceTrajectoryResult
    (cl:cons ':success (success msg))
))
