# CMake generated Testfile for 
# Source directory: /root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description
# Build directory: /root/share/catkin_ws/build_isolated/ur_description
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur10e.xml "/root/share/catkin_ws/build_isolated/ur_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur10e.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur10e.xml.xml\" \"/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/tests/roslaunch_test_ur10e.xml\" ")
set_tests_properties(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur10e.xml PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;10;roslaunch_add_file_check;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;0;")
add_test(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur10.xml "/root/share/catkin_ws/build_isolated/ur_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur10.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur10.xml.xml\" \"/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/tests/roslaunch_test_ur10.xml\" ")
set_tests_properties(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur10.xml PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;11;roslaunch_add_file_check;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;0;")
add_test(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur16e.xml "/root/share/catkin_ws/build_isolated/ur_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur16e.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur16e.xml.xml\" \"/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/tests/roslaunch_test_ur16e.xml\" ")
set_tests_properties(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur16e.xml PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;12;roslaunch_add_file_check;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;0;")
add_test(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur3e.xml "/root/share/catkin_ws/build_isolated/ur_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur3e.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur3e.xml.xml\" \"/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/tests/roslaunch_test_ur3e.xml\" ")
set_tests_properties(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur3e.xml PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;13;roslaunch_add_file_check;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;0;")
add_test(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur3.xml "/root/share/catkin_ws/build_isolated/ur_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur3.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur3.xml.xml\" \"/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/tests/roslaunch_test_ur3.xml\" ")
set_tests_properties(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur3.xml PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;14;roslaunch_add_file_check;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;0;")
add_test(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur5e.xml "/root/share/catkin_ws/build_isolated/ur_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur5e.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur5e.xml.xml\" \"/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/tests/roslaunch_test_ur5e.xml\" ")
set_tests_properties(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur5e.xml PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;15;roslaunch_add_file_check;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;0;")
add_test(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur5.xml "/root/share/catkin_ws/build_isolated/ur_description/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur5.xml.xml" "--return-code" "/usr/bin/cmake -E make_directory /root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/root/share/catkin_ws/build_isolated/ur_description/test_results/ur_description/roslaunch-check_tests_roslaunch_test_ur5.xml.xml\" \"/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/tests/roslaunch_test_ur5.xml\" ")
set_tests_properties(_ctest_ur_description_roslaunch-check_tests_roslaunch_test_ur5.xml PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;16;roslaunch_add_file_check;/root/share/catkin_ws/src/real/fmauch_universal_robot/ur_description/CMakeLists.txt;0;")
subdirs("gtest")
