FROM lhs223/unity_hub

# https://unity3d.com/get-unity/download/archive - check the version and changeset(in Release notes)
RUN unity-hub install --version 2021.1.12f1 --changeset afcadd793de6 --module linux-il2cpp standardassets