// Generated by gencpp from file niryo_one_msgs/DebugColorDetectionRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_DEBUGCOLORDETECTIONREQUEST_H
#define NIRYO_ONE_MSGS_MESSAGE_DEBUGCOLORDETECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct DebugColorDetectionRequest_
{
  typedef DebugColorDetectionRequest_<ContainerAllocator> Type;

  DebugColorDetectionRequest_()
    : color()  {
    }
  DebugColorDetectionRequest_(const ContainerAllocator& _alloc)
    : color(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DebugColorDetectionRequest_

typedef ::niryo_one_msgs::DebugColorDetectionRequest_<std::allocator<void> > DebugColorDetectionRequest;

typedef boost::shared_ptr< ::niryo_one_msgs::DebugColorDetectionRequest > DebugColorDetectionRequestPtr;
typedef boost::shared_ptr< ::niryo_one_msgs::DebugColorDetectionRequest const> DebugColorDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89e44dcab627a2c43a70ae1100695caa";
  }

  static const char* value(const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89e44dcab627a2c4ULL;
  static const uint64_t static_value2 = 0x3a70ae1100695caaULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/DebugColorDetectionRequest";
  }

  static const char* value(const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color\n"
;
  }

  static const char* value(const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DebugColorDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::DebugColorDetectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_DEBUGCOLORDETECTIONREQUEST_H
