// Generated by gencpp from file niryo_one_msgs/GetDigitalIORequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_GETDIGITALIOREQUEST_H
#define NIRYO_ONE_MSGS_MESSAGE_GETDIGITALIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct GetDigitalIORequest_
{
  typedef GetDigitalIORequest_<ContainerAllocator> Type;

  GetDigitalIORequest_()
    : pin(0)  {
    }
  GetDigitalIORequest_(const ContainerAllocator& _alloc)
    : pin(0)  {
  (void)_alloc;
    }



   typedef int32_t _pin_type;
  _pin_type pin;





  typedef boost::shared_ptr< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetDigitalIORequest_

typedef ::niryo_one_msgs::GetDigitalIORequest_<std::allocator<void> > GetDigitalIORequest;

typedef boost::shared_ptr< ::niryo_one_msgs::GetDigitalIORequest > GetDigitalIORequestPtr;
typedef boost::shared_ptr< ::niryo_one_msgs::GetDigitalIORequest const> GetDigitalIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.pin == rhs.pin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8921a2ed89c1a30dd6fec7e140bf82c6";
  }

  static const char* value(const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8921a2ed89c1a30dULL;
  static const uint64_t static_value2 = 0xd6fec7e140bf82c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/GetDigitalIORequest";
  }

  static const char* value(const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pin\n"
;
  }

  static const char* value(const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDigitalIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::GetDigitalIORequest_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_GETDIGITALIOREQUEST_H
