// Generated by gencpp from file niryo_one_msgs/GetPositionListResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_GETPOSITIONLISTRESPONSE_H
#define NIRYO_ONE_MSGS_MESSAGE_GETPOSITIONLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_one_msgs/Position.h>

namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct GetPositionListResponse_
{
  typedef GetPositionListResponse_<ContainerAllocator> Type;

  GetPositionListResponse_()
    : positions()  {
    }
  GetPositionListResponse_(const ContainerAllocator& _alloc)
    : positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::niryo_one_msgs::Position_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_one_msgs::Position_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionListResponse_

typedef ::niryo_one_msgs::GetPositionListResponse_<std::allocator<void> > GetPositionListResponse;

typedef boost::shared_ptr< ::niryo_one_msgs::GetPositionListResponse > GetPositionListResponsePtr;
typedef boost::shared_ptr< ::niryo_one_msgs::GetPositionListResponse const> GetPositionListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94fc33768181f413c5377ded0d0f7df2";
  }

  static const char* value(const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94fc33768181f413ULL;
  static const uint64_t static_value2 = 0xc5377ded0d0f7df2ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/GetPositionListResponse";
  }

  static const char* value(const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/Position[] positions\n"
"\n"
"\n"
"================================================================================\n"
"MSG: niryo_one_msgs/Position\n"
"string name\n"
"\n"
"float64[] joints \n"
"niryo_one_msgs/RPY rpy\n"
"geometry_msgs/Point point\n"
"geometry_msgs/Quaternion quaternion\n"
"\n"
"\n"
"================================================================================\n"
"MSG: niryo_one_msgs/RPY\n"
"# roll, pitch and yaw\n"
"\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::GetPositionListResponse_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_one_msgs::Position_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_GETPOSITIONLISTRESPONSE_H
