// Generated by gencpp from file niryo_one_msgs/GetSequenceListRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_GETSEQUENCELISTREQUEST_H
#define NIRYO_ONE_MSGS_MESSAGE_GETSEQUENCELISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct GetSequenceListRequest_
{
  typedef GetSequenceListRequest_<ContainerAllocator> Type;

  GetSequenceListRequest_()
    : info_header_only(false)  {
    }
  GetSequenceListRequest_(const ContainerAllocator& _alloc)
    : info_header_only(false)  {
  (void)_alloc;
    }



   typedef uint8_t _info_header_only_type;
  _info_header_only_type info_header_only;





  typedef boost::shared_ptr< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSequenceListRequest_

typedef ::niryo_one_msgs::GetSequenceListRequest_<std::allocator<void> > GetSequenceListRequest;

typedef boost::shared_ptr< ::niryo_one_msgs::GetSequenceListRequest > GetSequenceListRequestPtr;
typedef boost::shared_ptr< ::niryo_one_msgs::GetSequenceListRequest const> GetSequenceListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.info_header_only == rhs.info_header_only;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4fb5fb836b8f25a9ed3470500197359";
  }

  static const char* value(const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4fb5fb836b8f25aULL;
  static const uint64_t static_value2 = 0x9ed3470500197359ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/GetSequenceListRequest";
  }

  static const char* value(const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool info_header_only\n"
;
  }

  static const char* value(const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info_header_only);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSequenceListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::GetSequenceListRequest_<ContainerAllocator>& v)
  {
    s << indent << "info_header_only: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.info_header_only);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_GETSEQUENCELISTREQUEST_H
