// Generated by gencpp from file niryo_one_msgs/GetWorkspaceListResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_GETWORKSPACELISTRESPONSE_H
#define NIRYO_ONE_MSGS_MESSAGE_GETWORKSPACELISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct GetWorkspaceListResponse_
{
  typedef GetWorkspaceListResponse_<ContainerAllocator> Type;

  GetWorkspaceListResponse_()
    : workspaces()  {
    }
  GetWorkspaceListResponse_(const ContainerAllocator& _alloc)
    : workspaces(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _workspaces_type;
  _workspaces_type workspaces;





  typedef boost::shared_ptr< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWorkspaceListResponse_

typedef ::niryo_one_msgs::GetWorkspaceListResponse_<std::allocator<void> > GetWorkspaceListResponse;

typedef boost::shared_ptr< ::niryo_one_msgs::GetWorkspaceListResponse > GetWorkspaceListResponsePtr;
typedef boost::shared_ptr< ::niryo_one_msgs::GetWorkspaceListResponse const> GetWorkspaceListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.workspaces == rhs.workspaces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b36c598e23fd962676550874c6879f7";
  }

  static const char* value(const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b36c598e23fd962ULL;
  static const uint64_t static_value2 = 0x676550874c6879f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/GetWorkspaceListResponse";
  }

  static const char* value(const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] workspaces\n"
"\n"
;
  }

  static const char* value(const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.workspaces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWorkspaceListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::GetWorkspaceListResponse_<ContainerAllocator>& v)
  {
    s << indent << "workspaces[]" << std::endl;
    for (size_t i = 0; i < v.workspaces.size(); ++i)
    {
      s << indent << "  workspaces[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.workspaces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_GETWORKSPACELISTRESPONSE_H
