// Generated by gencpp from file niryo_one_msgs/JoystickJointsGoal.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_JOYSTICKJOINTSGOAL_H
#define NIRYO_ONE_MSGS_MESSAGE_JOYSTICKJOINTSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct JoystickJointsGoal_
{
  typedef JoystickJointsGoal_<ContainerAllocator> Type;

  JoystickJointsGoal_()
    : joy_values()
    , duration(0.0)  {
    }
  JoystickJointsGoal_(const ContainerAllocator& _alloc)
    : joy_values(_alloc)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joy_values_type;
  _joy_values_type joy_values;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JoystickJointsGoal_

typedef ::niryo_one_msgs::JoystickJointsGoal_<std::allocator<void> > JoystickJointsGoal;

typedef boost::shared_ptr< ::niryo_one_msgs::JoystickJointsGoal > JoystickJointsGoalPtr;
typedef boost::shared_ptr< ::niryo_one_msgs::JoystickJointsGoal const> JoystickJointsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.joy_values == rhs.joy_values &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48902d2eecaa07a469c0be86ecc527ec";
  }

  static const char* value(const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48902d2eecaa07a4ULL;
  static const uint64_t static_value2 = 0x69c0be86ecc527ecULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/JoystickJointsGoal";
  }

  static const char* value(const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"float64[] joy_values\n"
"float64 duration\n"
;
  }

  static const char* value(const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joy_values);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoystickJointsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::JoystickJointsGoal_<ContainerAllocator>& v)
  {
    s << indent << "joy_values[]" << std::endl;
    for (size_t i = 0; i < v.joy_values.size(); ++i)
    {
      s << indent << "  joy_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joy_values[i]);
    }
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_JOYSTICKJOINTSGOAL_H
