// Generated by gencpp from file niryo_one_msgs/SetLedsRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_SETLEDSREQUEST_H
#define NIRYO_ONE_MSGS_MESSAGE_SETLEDSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct SetLedsRequest_
{
  typedef SetLedsRequest_<ContainerAllocator> Type;

  SetLedsRequest_()
    : values()  {
    }
  SetLedsRequest_(const ContainerAllocator& _alloc)
    : values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLedsRequest_

typedef ::niryo_one_msgs::SetLedsRequest_<std::allocator<void> > SetLedsRequest;

typedef boost::shared_ptr< ::niryo_one_msgs::SetLedsRequest > SetLedsRequestPtr;
typedef boost::shared_ptr< ::niryo_one_msgs::SetLedsRequest const> SetLedsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dd1053b3769329bd3895728a55810d3";
  }

  static const char* value(const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dd1053b3769329bULL;
  static const uint64_t static_value2 = 0xd3895728a55810d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/SetLedsRequest";
  }

  static const char* value(const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] values\n"
;
  }

  static const char* value(const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLedsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::SetLedsRequest_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_SETLEDSREQUEST_H
