// Generated by gencpp from file niryo_one_msgs/UpdateConveyorIdResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_UPDATECONVEYORIDRESPONSE_H
#define NIRYO_ONE_MSGS_MESSAGE_UPDATECONVEYORIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_one_msgs
{
template <class ContainerAllocator>
struct UpdateConveyorIdResponse_
{
  typedef UpdateConveyorIdResponse_<ContainerAllocator> Type;

  UpdateConveyorIdResponse_()
    : status(0)
    , message()  {
    }
  UpdateConveyorIdResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateConveyorIdResponse_

typedef ::niryo_one_msgs::UpdateConveyorIdResponse_<std::allocator<void> > UpdateConveyorIdResponse;

typedef boost::shared_ptr< ::niryo_one_msgs::UpdateConveyorIdResponse > UpdateConveyorIdResponsePtr;
typedef boost::shared_ptr< ::niryo_one_msgs::UpdateConveyorIdResponse const> UpdateConveyorIdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator1> & lhs, const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_one_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "684cd572f268bd9685a29b0430c41747";
  }

  static const char* value(const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x684cd572f268bd96ULL;
  static const uint64_t static_value2 = 0x85a29b0430c41747ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_one_msgs/UpdateConveyorIdResponse";
  }

  static const char* value(const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n"
"string message\n"
;
  }

  static const char* value(const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateConveyorIdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_one_msgs::UpdateConveyorIdResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_UPDATECONVEYORIDRESPONSE_H
