alias eb='gedit ~/.bashrc'
alias sb='source ~/.bashrc'
export DISPLAY=:0

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/root/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/root/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/root/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/root/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

source /opt/ros/noetic/setup.bash
alias cm='catkin_make'
alias sd='source devel/setup.bash'
alias cw='cd ~/share/catkin_ws'
alias cw3='cd ~/share/python3_ws'
alias rg='rqt_graph'
alias tree='rosrun rqt_tf_tree rqt_tf_tree'
alias cmi='cd ~/catkin_ws && catkin_make_isolated'
alias sdi='source ~/catkin_ws/devel_isolated/setup.bash'
alias ppo='cd ~/share/pkgs/residual_shared_autonomy/ppo/'
source /opt/ros/noetic/setup.bash
source ~/share/catkin_ws/devel/setup.bash

export PYTHONPATH="${PYTHONPATH}:/root/share/pkgs:/root/share/catkin_ws/src"
