(cl:defpackage ur10_python_interface-msg
  (:use )
  (:export
   "<ELLIPSOID3>"
   "ELLIPSOID3"
   "<ROBOTIQ2FGRIPPER_ROBOT_INPUT>"
   "ROBOTIQ2FGRIPPER_ROBOT_INPUT"
   "<ROBOTIQ2FGRIPPER_ROBOT_OUTPUT>"
   "ROBOTIQ2FGRIPPER_ROBOT_OUTPUT"
  ))

